AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Serverless Job Queue System

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    MemorySize: 256
    Environment:
      Variables:
        JOBS_TABLE: !Ref JobsTable
        JOBS_QUEUE: !Ref JobsQueue

Resources:
  # DynamoDB Table
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: jobs
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # SQS Queue
  JobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: jobs-queue
      VisibilityTimeout: 60

  # API Gateway
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  # Lambda Functions
  SubmitJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambdas.submit_job.handler
      Events:
        SubmitJobApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /jobs
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt JobsQueue.QueueName

  ProcessJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambdas.process_job.handler
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt JobsQueue.Arn
            BatchSize: 1
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable

  GetJobStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambdas.get_status.handler
      Events:
        GetJobApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /jobs/{job_id}
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref JobsTable

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  JobsTableName:
    Description: DynamoDB table name
    Value: !Ref JobsTable
  JobsQueueUrl:
    Description: SQS queue URL
    Value: !Ref JobsQueue 